### ISSUE TITLE
PigZombies Not dropping pork.

### ISSUE THREAD

**Issue by daemitus** [LexManos/DwarfCraft#10]
Line 313? EntityListener.
Upon death, ALL entities receive items.clear(); and the animal/monster hunter repopulates their loot table.
Solution? add pigzombies to monster hunter or add a if catch for them.

**Comment by daemitus** [comment]
Apparently fixed.

**Comment by LexManos** [comment]
Nice catch, Fixed in: 
https://github.com/LexManos/DwarfCraft/commit/8cffdcda95f3336a3fe61b254176c4e3fb40e899
I need to plan a set of nether related skills for Ghasts, Pigmen, Soulsand, Lightstone, and Netherack.
