### ISSUE TITLE
SQL conversion from old->new

### ISSUE THREAD

**Issue by daemitus** [LexManos/DwarfCraft#2]
Players, trainers worked fine. No skills were converted. When my admin sent me the dwarfcraft.db file to troubleshoot with, the Skills table was empty

**Comment by LexManos** [comment]
The database should be converted automatically. Can you please provide your db file from before and after?
I have tested it on a DB from a server with 2,000 people and it converted fine. So I would like your file to debug with.

**Comment by daemitus** [comment]
I wish, my admin was smart enough to not backup, otherwise I wouldnt be 
as cranky. hah.
Mind making me a branch in your project so I can crank out the vehicle 
destroy event? Id rather not have to fork your project as well as 
smartaleq's and request pulls. I meant to grab your attention last night 
when you were testing the server, but i missed you.

**Comment by LexManos** [comment]
Ah, everyone should always backup, Also testing offline is a good idea.
Anyways, Go the pull request route. I'd rather not immediately give out contributers before seeing what they will do with it.

**Comment by daemitus** [comment]
If you scan back through the DC thread, I had posted the semi-working 
1.4 version before you got involved.
