### ISSUE TITLE
Vehicle Destroy event

### ISSUE THREAD

**Issue by daemitus** [LexManos/DwarfCraft#3]
As with smartaleq's version, the destroy event is only a stub, so the sailor skill is partially broken.

**Comment by daemitus** [comment]
Bukkit does not have boats register vehicledestroyevents as of 1 May, issue opened at Bukkit, event handling on this end should be good.

Pull requested, needs final testing once event works properly. Code is commented for the time being.

**Comment by LexManos** [comment]
Commited here: https://github.com/LexManos/DwarfCraft/commit/00f56b4e2a023bc438ef913f1b30ab61d87b15e4
Tested locally and it does fire for boats so it should be working now.
